# Generated by Django 5.0.7 on 2024-09-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='datos_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
    ]
