# Generated by Django 5.0.7 on 2024-09-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_pedido_datos_entrega_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='sabor_alita_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='sabor_alita_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='sabor_bebida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
