# Generated by Django 5.0.7 on 2024-07-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(choices=[('Combos fin de semana', 'Combos fin de semana'), ('Pizza', 'Pizza'), ('Alitas', 'Alitas'), ('Combos diarios', 'Combos diarios'), ('Bebidas', 'Bebidas'), ('Promociones', 'Promociones')], default='', max_length=70),
        ),
    ]
