# Generated by Django 5.0.7 on 2024-07-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_categoria_nombre_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='decription',
            new_name='deScription',
        ),
    ]
