# Generated by Django 5.0.7 on 2024-07-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_decription_categoria_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='deScription',
            new_name='description',
        ),
    ]
