# Generated by Django 5.0.7 on 2024-07-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_description_categoria_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='', upload_to='producto'),
        ),
    ]
