# Generated by Django 5.0.7 on 2024-08-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_categoria_nombre_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_atributo', models.CharField(max_length=100)),
                ('valor_atributo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='atributos',
            field=models.ManyToManyField(blank=True, to='menu.atributo'),
        ),
    ]
