# Generated by Django 5.0.7 on 2024-08-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_atributo_producto_atributos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='atributos',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='sabor',
            field=models.CharField(blank=True, choices=[('TRC', 'Tres Carnes'), ('CHA', 'Champiñones'), ('HAW', 'Hawaiana'), ('PEP', 'Pepperoni'), ('TQ', 'Tres Quesos'), ('CHO', 'Chorizo')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(blank=True, choices=[('PE', 'Pequeña'), ('ME', 'Mediana'), ('FA', 'Familiar')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Atributo',
        ),
    ]
