# Generated by Django 5.0.7 on 2024-08-11 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_remove_producto_atributos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sabor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tamaño',
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(choices=[('PE', 'Pequeña'), ('ME', 'Mediana'), ('FA', 'Familiar')], max_length=2)),
                ('sabor', models.CharField(choices=[('TRC', 'Tres Carnes'), ('CHA', 'Champiñones'), ('HAW', 'Hawaiana'), ('PEP', 'Pepperoni'), ('TQ', 'Tres Quesos'), ('CHO', 'Chorizo')], max_length=3)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
    ]
