# Generated by Django 5.0.7 on 2024-08-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_producto_sabor_remove_producto_tamaño_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='tamaño',
        ),
    ]
