# Generated by Django 5.0.7 on 2024-08-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_remove_pizza_tamaño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='sabor',
            new_name='sabor_1',
        ),
        migrations.AddField(
            model_name='pizza',
            name='sabor_2',
            field=models.CharField(choices=[('TRC', 'Tres Carnes'), ('CHA', 'Champiñones'), ('HAW', 'Hawaiana'), ('PEP', 'Pepperoni'), ('TQ', 'Tres Quesos'), ('CHO', 'Chorizo')], default=2, max_length=3),
            preserve_default=False,
        ),
    ]
