# Generated by Django 5.0.7 on 2024-08-12 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(choices=[('CCC', 'Coca COla'), ('FNT', 'Fanta'), ('FIO', 'Fiora'), ('SPR', 'Sprite'), ('INK', 'Inka')], max_length=3)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
    ]
