# Generated by Django 5.0.7 on 2024-08-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_pizza_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alitas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto'),
        ),
    ]
