# Generated by Django 5.0.7 on 2024-09-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_alitas_producto_alter_bebida_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alitas',
            name='sabor_1',
            field=models.CharField(choices=[('BBQ', 'BBQ'), ('Miel y Mostaza', 'Miel y Mostaza'), ('Macaruyá', 'Macaruyá'), ('Broster', 'Broster'), ('Piña', 'Piña')], max_length=15),
        ),
        migrations.AlterField(
            model_name='alitas',
            name='sabor_2',
            field=models.CharField(choices=[('BBQ', 'BBQ'), ('Miel y Mostaza', 'Miel y Mostaza'), ('Macaruyá', 'Macaruyá'), ('Broster', 'Broster'), ('Piña', 'Piña')], max_length=15),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='sabor',
            field=models.CharField(choices=[('Coca Cola', 'Coca Cola'), ('Fanta', 'Fanta'), ('Fiora', 'Fiora'), ('Sprite', 'Sprite'), ('Inka', 'Inka')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sabor_1',
            field=models.CharField(choices=[('Tres Carnes', 'Tres Carnes'), ('Champiñones', 'Champiñones'), ('Hawaiana', 'Hawaiana'), ('Pepperoni', 'Pepperoni'), ('Tres Quesos', 'Tres Quesos'), ('Chorizo', 'Chorizo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sabor_2',
            field=models.CharField(choices=[('Tres Carnes', 'Tres Carnes'), ('Champiñones', 'Champiñones'), ('Hawaiana', 'Hawaiana'), ('Pepperoni', 'Pepperoni'), ('Tres Quesos', 'Tres Quesos'), ('Chorizo', 'Chorizo')], max_length=15),
        ),
    ]
