# Generated by Django 5.0.7 on 2024-09-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_alitas_sabor_1_alter_alitas_sabor_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_sabor_1', models.CharField(choices=[('Tres Carnes', 'Tres Carnes'), ('Champiñones', 'Champiñones'), ('Hawaiana', 'Hawaiana'), ('Pepperoni', 'Pepperoni'), ('Tres Quesos', 'Tres Quesos'), ('Chorizo', 'Chorizo')], max_length=15)),
                ('pizza_sabor_2', models.CharField(choices=[('Tres Carnes', 'Tres Carnes'), ('Champiñones', 'Champiñones'), ('Hawaiana', 'Hawaiana'), ('Pepperoni', 'Pepperoni'), ('Tres Quesos', 'Tres Quesos'), ('Chorizo', 'Chorizo')], max_length=15)),
                ('alita_sabor_1', models.CharField(choices=[('BBQ', 'BBQ'), ('Miel y Mostaza', 'Miel y Mostaza'), ('Macaruyá', 'Macaruyá'), ('Broster', 'Broster'), ('Piña', 'Piña')], max_length=15)),
                ('alita_sabor_2', models.CharField(choices=[('BBQ', 'BBQ'), ('Miel y Mostaza', 'Miel y Mostaza'), ('Macaruyá', 'Macaruyá'), ('Broster', 'Broster'), ('Piña', 'Piña')], max_length=15)),
                ('bebida_sabor', models.CharField(choices=[('Coca Cola', 'Coca Cola'), ('Fanta', 'Fanta'), ('Fiora', 'Fiora'), ('Sprite', 'Sprite'), ('Inka', 'Inka')], max_length=15)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
    ]
